services:
  - type: web
    name: gpu-radar-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /api/products?name=RTX
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: DATABASE_HOST
        fromDatabase:
          name: gpu-radar-db
          property: host

      - key: DATABASE_PORT
        fromDatabase:
          name: gpu-radar-db
          property: port

      - key: DATABASE_NAME
        fromDatabase:
          name: gpu-radar-db
          property: database

      - key: DATABASE_USERNAME
        fromDatabase:
          name: gpu-radar-db
          property: user

      - key: DATABASE_PASSWORD
        fromDatabase:
          name: gpu-radar-db
          property: password

      - key: JWT_SECRET
        generateValue: true

      - key: SERPAPI_KEY
        sync: false

  - type: static
    name: gpu-radar-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://gpu-radar-api.onrender.com/api/*

      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: gpu-radar-db
    plan: free
    databaseName: gpuradar
    user: gpuradar