spring.application.name=gpu-radar-api

# ======================
# LOCAL SECRETS
# ======================
spring.config.import=optional:classpath:application-secrets.properties

# ======================
# POSTGRESQL
# ======================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/gpu_radar}
spring.datasource.username=${DATABASE_USERNAME:gpu_radar}
spring.datasource.password=${DATABASE_PASSWORD:gpu_radar}

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# SERPAPI
# ======================
serpapi.base-url=https://serpapi.com
serpapi.api-key=${SERPAPI_KEY:${serpapi.local-api-key:}}

# ======================
# SERVER
# ======================
server.port=8080

# ======================
# LOGGING
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE