spring.application.name=gpu-radar-api

# ======================
# JWT
# ======================
jwt.secret=${JWT_SECRET:my-super-secret-key-my-super-secret-key}
jwt.expiration=86400000

# ======================
# LOCAL SECRETS
# ======================
spring.config.import=optional:classpath:application-secrets.properties

# ======================
# POSTGRESQL
# ======================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# SERPAPI
# ======================
serpapi.base-url=https://serpapi.com
serpapi.api-key=${SERPAPI_KEY:${serpapi.local-api-key:}}

# ======================
# SERVER
# ======================
server.port=${PORT:8080}

# ======================
# LOGGING
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE